all:
  children:
    controller:
      hosts:
        ctl-laptop:
          ansible_connection: local
          ansible_user: operator

    hypervisor:
      hosts:
        hypervisor-01:
          ansible_host: hypervisor-01.example.net
          ansible_user: root

    backup_appliance:
      hosts:
        backup-01:
          ansible_host: backup-01.example.net
          ansible_user: root

    edge_firewall:
      hosts:
        edge-fw-01:
          ansible_host: edge-fw-01.example.net
          ansible_user: ansible
          ansible_connection: ssh
          ansible_shell_type: sh
          ansible_python_interpreter: none

    identity:
      hosts:
        dc-01:
          ansible_host: 192.0.2.222
          ansible_user: admin

    mail:
      hosts:
        mail-01:
          ansible_host: 192.0.2.210
          ansible_user: debian

    siem:
      hosts:
        siem-01:
          ansible_host: 192.0.2.225
          ansible_user: debian

    case_mgmt:
      hosts:
        soc-01:
          ansible_host: 192.0.2.226
          ansible_user: debian

    threat_intel:
      hosts:
        intel-01:
          ansible_host: 192.0.2.227
          ansible_user: debian

    automation:
      hosts:
        soc-01:
          ansible_host: 192.0.2.226
          ansible_user: debian

    lab_router:
      hosts:
        lab-router-01:
          ansible_host: 192.0.2.252
          ansible_user: debian

    linux_endpoints:
      children:
        mail:
        siem:
        case_mgmt:
        threat_intel:
        automation:
        lab_router:
        backup_appliance:
        hypervisor:

    windows_domain_controllers:
      hosts:
        dc-01:
          ansible_host: 192.0.2.222

    windows_workstations:
      hosts:
        ws-01:
          ansible_host: 192.0.2.223
        ws-02:
          ansible_host: 192.0.2.224

    windows_endpoints:
      children:
        windows_domain_controllers:
        windows_workstations:
